<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

//echo $block->getAjaxLoader();exit;
$mediaUrl = $block ->_storeManager-> getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );

$faqsColection = $block->getProductPageFaqs($block->getProductId());
$answerLengthAllowed = $block->allowedAnswerLength();

$count = 1;

//$block->getLoginUserId();
/*if($block->getLoginUserId()){echo "Login";}
else{echo "not login";}
exit;*/
?>



  <head>
  <script type="text/javascript">
      
      require([
            'jquery'
            ], function ($) {


   window.onload = function capt() {
      
       
       var exists = document.getElementById("recaptcha");
        var captachakey = "<?php echo $block->getPublicKey()?>";
        if(exists){
             widgetId1 = grecaptcha.render('recaptcha', {
          'sitekey' : captachakey,
          'theme' : 'light'
        });


              $('input[name^="faqs"]').each( function() {
            widgetId2 = grecaptcha.render(document.getElementById('recaptcha2'+this.value), {
          'sitekey' : captachakey
        });
          
        });


        }
       
    
       

         $("ul").each(function(n) {
              
           // $(this).find("#ui-accordion-accordion_element-panel-"+n).height('auto');
            $("#ui-accordion-accordion_element-panel-"+n).css("height", 'auto');
      });

        $('input[name^="faqs"]').each( function() {
            var temp = this.value;
        $( "#fme-ask-answer-form-wraper"+this.value).on('submit', function( event ) {

                    
                    var count = document.getElementById("count"+temp).value;

                     var exists = document.getElementById("g-recaptcha-response-"+count);

            if(exists == null){
                       var form = $( "#fme-ask-answer-form"+temp );

                        $("#progress-loader2"+temp).addClass('progress-loader2');  
                        
                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getAnswerPostUrl() ?>",
                                data: form.serialize()
                        }).done(function( res ) {

                                if(res.error === false){

                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-fail')){
                                        $('#faq-response2'+temp).removeClass('rate-fail');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-success');


                                }else{
                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-success')){
                                        $('#faq-response2'+temp).removeClass('rate-success');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-fail');                                
                                }   
                                
                                $("#progress-loader2"+temp).removeClass('progress-loader2');  
                        });

                    event.preventDefault();
            }
        
             else{

            var check = document.getElementById("g-recaptcha-response-"+count).value;
           
                if(check=='' || check == null){
                   
                }
                else{
                        

                      var form = $( "#fme-ask-answer-form"+temp );
                       
                        $("#progress-loader2"+temp).addClass('progress-loader2');  
                       
                        
                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getAnswerPostUrl() ?>",
                                data: form.serialize()
                        }).done(function( res ) {

                                if(res.error === false){

                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-fail')){
                                        $('#faq-response2'+temp).removeClass('rate-fail');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-success');


                                }else{
                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-success')){
                                        $('#faq-response2'+temp).removeClass('rate-success');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-fail');                                
                                }   
                                
                                $("#progress-loader2"+temp).removeClass('progress-loader2'); 

                                
                        });

                    event.preventDefault();
                }
            }

                });
        
         });


    }

    function capt2() {
      
        //alert("capthca render");
        var exists = document.getElementById("recaptcha");
        var captachakey = "<?php echo $block->getPublicKey()?>";
       
       if(exists){

           $('input[name^="faqs"]').each( function() {
            widgetId2 = grecaptcha.render(document.getElementById('recaptcha2'+this.value), {
          'sitekey' : captachakey
        });
            

        });

       }
       

        

        $('input[name^="faqs"]').each( function() {
            var temp = this.value;
        $( "#fme-ask-answer-form-wraper"+this.value).on('submit', function( event ) {

        var myForm = document.getElementById("fme-ask-answer-form"+temp);


        //var count = document.getElementById("count"+val).value;
        var exists = myForm.elements[9].value;


                    var count = document.getElementById("count"+temp).value;
                    
                    // var exists = document.getElementById("g-recaptcha-response-"+count);

            if(exists == null){
                       var form = $( "#fme-ask-answer-form"+temp );

                        $("#progress-loader2"+temp).addClass('progress-loader2');  
                        
                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getAnswerPostUrl() ?>",
                                data: form.serialize()
                        }).done(function( res ) {

                                if(res.error === false){

                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-fail')){
                                        $('#faq-response2'+temp).removeClass('rate-fail');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-success');


                                }else{
                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-success')){
                                        $('#faq-response2'+temp).removeClass('rate-success');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-fail');                                
                                }   
                                
                                $("#progress-loader2"+temp).removeClass('progress-loader2');  
                        });

                    event.preventDefault();
            }
        
             else{
                var check = exists;
         //   var check = document.getElementById("g-recaptcha-response-"+count).value;
           
                if(check=='' || check == null){
                   
                }
                else{
                        

                      var form = $( "#fme-ask-answer-form"+temp );
                       
                        $("#progress-loader2"+temp).addClass('progress-loader2');  
                       
                        
                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getAnswerPostUrl() ?>",
                                data: form.serialize()
                        }).done(function( res ) {

                                if(res.error === false){

                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-fail')){
                                        $('#faq-response2'+temp).removeClass('rate-fail');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-success');


                                }else{
                                    $('#faq-response2'+temp).text(res.message);
                                    if($('#faq-response2'+temp).hasClass('rate-success')){
                                        $('#faq-response2'+temp).removeClass('rate-success');
                                    }
                                    $('#faq-response2'+temp).addClass('rate-fail');                                
                                }   
                                
                                $("#progress-loader2"+temp).removeClass('progress-loader2'); 

                                
                        });

                    event.preventDefault();
                }
            }

                });
        
         });


    }

            $('#jumpMenu').on('change', function() {
           var proid = "<?php echo $block->getProductId()?>";
           var sortbyarrow = $('#sortby').val();
           var ajaxloader = "<?php echo $mediaUrl."prodfaqs/ajax/".$block->getAjaxLoader()?>";
          
          
            
           
              $("#data-loader").css("background", "url("+ajaxloader+") no-repeat");
               $("#data-loader").addClass('data-loader'); 
             
             
             $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getAjaxUrl() ?>",
                                data: { value: this.value , proid: proid , sortbyarrow: sortbyarrow}
                        }).done(function( res ) {
                            
                            //alert(res.Data);
                            //capt2();
                              $("#data-loader").removeClass('data-loader');  
                            $('#ajax').html('');
                             $('#ajax').html(res.Data);
                             capt2();
                                if(res.error === false){

                                   // alert(res.error);
                                 
                                                                 
                                }
                                else{
                                    // alert(res.message);
                                }

                                  

                        });

        })


        $( "#sortby" ).on( "click", function() {
            if(document.getElementById("sortby").className == 'sortbyasc'){

              $('#sortby').attr('title','Descending');

                document.getElementById('sortby').classList.add('sortbydesc');
            document.getElementById('sortby').classList.remove('sortbyasc');

             document.getElementById('sortby').value = 'desc';

             var val1 = document.getElementById('jumpMenu').value 
             var proid = "<?php echo $block->getProductId()?>";
             var sortbyarrow = 'desc';
              var ajaxloader = "<?php echo $mediaUrl."prodfaqs/ajax/".$block->getAjaxLoader()?>";
             $("#data-loader").css("background", "url("+ajaxloader+") no-repeat");
             $("#data-loader").addClass('data-loader');  
              $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getAjaxUrl() ?>",
                                data: { value: this.value , proid: proid , sortbyarrow: sortbyarrow}
                        }).done(function( res ) {
                            
                            //alert(res.Data);
                             $("#data-loader").removeClass('data-loader');
                             $('#ajax').html('');
                             $('#ajax').html(res.Data);
                             capt2();
                                if(res.error === false){

                                    //alert(res.error);
                                                                  
                                }
                                else{
                                    // alert(res.message);
                                }

                                  

                        });

            }
            else if(document.getElementById("sortby").className == 'sortbydesc'){
                document.getElementById('sortby').classList.add('sortbyasc');
            document.getElementById('sortby').classList.remove('sortbydesc');
            document.getElementById('sortby').value = 'asc';
            $('#sortby').attr('title','Ascending');
                    var val1 = document.getElementById('jumpMenu').value 
             var proid = "<?php echo $block->getProductId()?>";
             var sortbyarrow = 'asc';
              var ajaxloader = "<?php echo $mediaUrl."prodfaqs/ajax/".$block->getAjaxLoader()?>";
             $("#data-loader").css("background", "url("+ajaxloader+") no-repeat");
               $("#data-loader").addClass('data-loader');  
              $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getAjaxUrl() ?>",
                                data: { value: val1 , proid: proid , sortbyarrow: sortbyarrow}
                        }).done(function( res ) {
                            
                           // alert(res.Data);
                             $("#data-loader").removeClass('data-loader');  
                             $('#ajax').html('');
                             $('#ajax').html(res.Data);
                             capt2();
                                if(res.error === false){

                                    
                                                                 
                                }
                                else{
                                    
                                }

                                  

                        });
            }
        });



});
        

       
  </script>
  </head>  
   

            <div class="faq_block" data-rating-role="rating-placeholder">
                    
                <div id="rating-response"></div>
                
                <h2 style="text-align: left;float: left;"><?php echo $block->getProductFaqsHeading(); ?></h2>


                <?php if($block->isAskQuestionEnable() && $block->isAskQuestionAllowed()): ?>
                
    <div class="ask-question-form <?php if($block->openFormPopupSlide() != 'slide'): ?> mfp-hide white-popup-block <?php endif ?>" id="fme-ask-question-form-wraper" style="<?php if($block->openFormPopupSlide() == 'slide'): ?> display:none <?php endif ?>" >
    
            <form action="<?php echo $block->getFaqPostUrl() ?>" id="fme-ask-question-form" name="fme-ask-question-form" onsubmit="return myFunction()" method="post" enctype="multipart/form-data" class="review-form">
            
            
            <input name="status" id="status" value="0" type="hidden"  />
            <input name="product_id" id="product_id" value="<?php echo $block->getProductId(); ?>" type="hidden"  />
            <input name="question_type" id="question_type" value="product_question" type="hidden"  />
            <input name="product_url" id="product_url" value="<?php echo $block->getProductUrl(); ?>" type="hidden"  />
            <input name="product_name" id="product_name" value="<?php echo $block->getProductName(); ?>" type="hidden"  />
                        
            <div class="fieldset">
                <h2 class="legend"><?php echo __('Ask a Question') ?></h2>
                
                <div id="faq-response" class=""></div>  
                        
                        <div class="field required">
                            <label for="customer_name" class="label"><?php echo __('Name') ?></label>
                            <div class="control">
                                <input name="customer_name" id="customer_name" title="<?php echo __('Customer Name ') ?>" value="<?php if($block->getLoginId()){echo $block->getLoginName();} ?>" class="input-text" data-validate="{required:true}" type="text" />
                            </div>
                        </div>
                        
                        <div class="field required">
                            <label for="customer_email"  class="label"><?php echo __('Email') ?></label>
                            <div class="control">
                            <input name="customer_email" id="customer_email" title="<?php echo __('Customer Email') ?>" value="<?php if($block->getLoginId()){echo $block->getLoginEmail();}?>" class="input-text" data-validate="{required:true, 'validate-email':true}" type="text" />
                            </div>
                        </div>
                                                        
                                                <div class="field required">
                                                    <label for="question" class="label"><?php echo __('Question') ?></label>
                                                    <div class="control">
                                                        <textarea name="question" id="question" title="<?php echo __('Question') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                                                    </div>
                                                </div>
                                                <input type="checkbox" name="isprivate">
                                                <label for="typee" style="font-weight: bold;" class="label"><?php echo __('Private Question') ?></label>
                                                <br><br><br>
                                                <?php if($block->isCaptchaEnable()): 
                                                    
                                                ?>
                                                
                                                 <div  name="recaptcha" id="recaptcha"></div> 
                                                 <br><br><br>
                                                <?php endif; ?>
                                
                                
                           
                                <button  type="submit"  title="<?php echo __('Submit') ?>" class="button"><span><?php echo __('Submit') ?></span></button>
                                <span id="progress-loader"></span>  
                            <input type="hidden" name="custid" value="<?php if( $block->getLoginId()){ echo $block->getLoginId(); } ?>">
            
            </div>
            <div class="clear"></div>
            
        </form>
        
            <script>

                require([
                    'jquery',
                    'mage/mage'
                ], function($){

                    var dataForm = $('#fme-ask-question-form');
                    var ignore = null;

                    dataForm.mage('validation', {
                            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                        }).find('input:text').attr('autocomplete', 'off');

                });
            </script>
            
    </div>
   
    <?php if($block->openFormPopupSlide() == 'slide'): ?>
            <p class="faqsaddslide" >
                    <a class="btn-slide add_question" style="color: white;text-decoration: none;" title="<?php echo __('Ask a Question') ?>" id="fme-faq-btn-slide-open" href="javascript: " onclick="if(jQuery('#fme-ask-question-form-wraper').css('display') == 'none'){ jQuery('#fme-ask-question-form-wraper').slideDown() }else{ jQuery('#fme-ask-question-form-wraper').slideUp(); }" ><?php echo __('Ask a Question'); ?></a>
            </p>
        <?php else: ?>
            <p class="faqsaddslide " >
                    <a style="color: white;text-decoration: none;"   class="btn-slide popup-with-form add_question" title="<?php echo __('Ask a Question') ?>" id="fme-faq-btn-popup-open" href="#fme-ask-question-form-wraper" ><?php echo __('Ask a Question'); ?></a>
            </p>
        <?php endif; ?>

    <?php endif; ?>

     <hr style="clear:both;"/>
                  <div class="sort_by">
          
            <form name="form" id="form">
            Sort by &nbsp;&nbsp;
              <select name="jumpMenu" id="jumpMenu" >
                <option value="0">Rating</option>
                <option value="1">Date</option>
              </select>
              <a href="javascript:void(0)" id="sortby" value="asc" title="Ascending"  onclick=""  class="sortbyasc">
        
                 </a>

            </form>
        </div>    
            <div class="" name="data-loader" id="data-loader"> </div>
            <div name="ajax" class="ajax" id="ajax">        
                
               <ul id="<?php echo 'accordion_element' ?>">
                    
                    <?php 

                        if($faqsColection->count() > 0){

                            foreach ($faqsColection as $faq){

                            $faqanswers = $block->getfaqanswers($faq->getId());                               
                                
                    ?>                            
                    <li>
                                <div class="accordion-toggle" ><?php echo $faq->getTitle(); ?>
                                    
                                    <?php if($block->isRatingEnable() ){ ?>
                                        <div class="br-theme-css-stars" style="float: right;">
                                            <select id="<?php echo $faq->getId(); ?>" data-stars-role="<?php echo (int) $faq->getRatingStars(); ?>" data-customer-rate-readonly="<?php echo $block->isCustomerReadonlyStars($faq->getId())?>">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                        

                                    <?php } ?>
                                </div>

                                <div  class="accordion-content" >
                                <div class="answered_by">Question by: <?php echo $faq->getQuestion_by(); ?> on <?php echo $faq->getCreate_date(); ?></div>

                                <?php
                                    foreach ($faqanswers as $ans) {
                                 ?>
                                    <div class="add_thread1">
                                    <p>
                                        <?php 
                                            $answer = $ans['answer']; 
                                            if($answerLengthAllowed == 0 || (strlen($answer) <= $answerLengthAllowed)):
                                                echo $answer;
                                            else:
                                                echo substr($answer, 0, $answerLengthAllowed).' <a title="'._("View Detail").'" href="'.$block->getFaqUrl($faq).'">...</a>';
                                            endif;  
                                        ?>
                                    </p>
                                    
                                
                                    
                                    <div  class="answered_by">Answer by: <?php echo $ans['answer_by']; ?> on <?php echo $ans['create_date']; ?></div>
                                    <?php if($block->isLikesEnable()) { ?>
                                    <div style="<?php if(!$block->isLikesAllowed() || $block->isCustomerReadonlyLikes($ans['answer_id'])){ echo 'pointer-events: none'; }?>" class="js-rating" data-ans="<?php echo $ans['answer_id']; ?>" data-like="<?php echo $ans['likes']; ?>" data-dislike="<?php echo $ans['dislikes']; ?>"></div>
                                        <?php } ?>
                                    </div>

                                   <?php } ?>
                                      <!-- Answer form -->

     <?php if($block->isAskAnswerEnable() && $block->isAskAnswerAllowed()): ?>
        
    <div class="ask-answer-form mfp-hide white-popup-block " id="fme-ask-answer-form-wraper<?php echo $faq->getId(); ?>" style=""  >
    
            <form action="javascript:void(0);" id="fme-ask-answer-form<?php echo $faq->getId(); ?>" name="fme-ask-answer-form<?php echo $faq->getId(); ?>" onsubmit="return myFunction2(<?php echo $faq->getId(); ?>)" method="post" enctype="multipart/form-data" class="review-form">
            
            
            <input name="status" id="status" value="0" type="hidden"  />
            <input name="faq_id" id="faq_id" value="<?php echo $faq->getID(); ?>" type="hidden"  />
            <input type="hidden" name="faqs[]" value="<?php echo $faq->getID(); ?>">
             <input type="hidden" name="count<?php echo $faq->getId(); ?>" id="count<?php echo $faq->getId(); ?>" value="<?php echo $count; ?>">
             <input name="faq_question" id="faq_question" value="this is question ?" type="hidden"  />
            <input name="product_url" id="product_url" value="<?php echo $block->getProductUrl(); ?>" type="hidden"  />
                        
            <div class="fieldset">
                <h2 class="legend"><?php echo __('Add answer') ?></h2>
                
                <div id="faq-response2<?php echo  $faq->getID(); ?>" class=""></div>  
                        
                        <div class="field required">
                            <label for="customer_name" class="label"><?php echo __('Name') ?></label>
                            <div class="control customer_name">
                                <input name="customer_name" id="customer_name" title="<?php echo __('Customer Name ') ?>" value="<?php if($block->getLoginId()){echo $block->getLoginName();} ?>" class="input-text" data-validate="{required:true}" type="text" />
                            </div>
                        </div>
                        
                        <div class="field required">
                            <label for="customer_email"  class="label"><?php echo __('Email') ?></label>
                            <div class="control">
                            <input name="customer_email" id="customer_email" title="<?php echo __('Customer Email') ?>" value="<?php if($block->getLoginId()){echo $block->getLoginEmail();}?>" class="input-text" data-validate="{required:true, 'validate-email':true}" type="text" />
                            </div>
                        </div>
                                                        
                                                <div class="field required">
                                                    <label for="answer" class="label"><?php echo __('Answer') ?></label>
                                                    <div class="control">
                                                        <textarea name="answer" id="answer" title="<?php echo __('Answer') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                                                    </div>
                                                </div>
                                                
                                                <?php if($block->isCaptchaEnable()): 
                                                    
                                                ?>
                                                
                                                 <div  name="recaptcha2" id="recaptcha2<?php echo $faq->getId(); ?>"></div> 
                                                 <br><br><br>
                                                <?php endif; ?>
                                
                                
                            
                                <button  type="submit" onclick="" id="<?php echo  $faq->getID(); ?>" value="<?php echo  $count; ?>" title="<?php echo __('Submit') ?>" class="button"><span><?php echo __('Submit') ?></span></button>
                                <span style="padding-left: 30px;" id="progress-loader2<?php echo  $faq->getID(); ?>"></span>  
                            <input type="hidden" name="custid" value="<?php echo $block->getLoginId(); ?>">
                            <?php $count++; ?>
            
            </div>
            <div class="clear"></div>
            
        </form>
        
            <script>

                require([
                    'jquery',
                    'mage/mage'
                ], function($){

                    var dataForm = $('#fme-ask-answer-form');
                    var ignore = null;

                    dataForm.mage('validation', {
                            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                        }).find('input:text').attr('autocomplete', 'off');

                });
            </script>
            
    </div>
    
    <?php if($block->openFormPopupSlide() == 'slide'): ?>
            <p class="faqsaddslide add_answer" >
                    <a class="btn-slide popup-with-form" title="<?php echo __('Add answer') ?>" id="fme-faq-btn-popup-open" href="#fme-ask-answer-form-wraper<?php echo $faq->getId(); ?>" ><?php echo __('Add answer'); ?></a>
            </p>
        <?php else: ?>
            <p class="faqsaddslide add_answer" >
                    <a class="btn-slide popup-with-form" title="<?php echo __('Add answer') ?>" id="fme-faq-btn-popup-open" href="#fme-ask-answer-form-wraper<?php echo $faq->getId(); ?>" ><?php echo __('Add answer'); ?></a>
            </p>
        <?php endif; ?>

    <?php endif; ?>
                                </div>

               
 
                    </li>
                    <?php
                                                                
                            }                        

                        }else{
                    ?>
                    
                            <div class="message notice">
                                <div>
                                    <?php echo __('There are no faqs for this topic.');  ?>
                                </div>
                            </div>
                            
                    <?php
                            
                        }

                    ?>
                </ul>     
                    </div>
                        
                
            </div>




    <!--Question Form Starts-->
    
    <!--Question Form Ends-->
   


  
    <!--Answer Form Ends-->          
    
<?php if($block->isAccordionEnable() ){ ?>

    <script>
        require([
            'jquery',
            'tabs'], function ($) {
            $(".faq_block ul").accordion();
        });    

    </script>

<?php } ?>


<?php if($block->isRatingEnable() ){ ?>

    <script>

        require([
            'jquery',
            'barrating'
            ], function ($) {

            $('.br-theme-css-stars select').barrating({
                theme : 'css-stars',
                initialRating : true, //get value from element's attribute 'data-stars-role'
               // readonly : <?php //echo $block->isCustomerRatingReadonly() ?>,
                onSelect : function(value, text, faq, event){

                    if(typeof(event) !== undefined){

                        $('#rating-response').text('');

                        //call ajax and save the rating for that FAQ
                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getRatingAjaxUrl() ?>",
                                data: { value: value, faq: faq }
                        }).done(function( res ) {

                                if(res.error === false){

                                    $('#rating-response').text(res.message);
                                    if($('#rating-response').hasClass('rate-fail')){
                                        $('#rating-response').removeClass('rate-fail');
                                    }
                                    $('#rating-response').addClass('rate-success');

                                    //make these stars readonly now
                                    $('#'+faq).barrating('readonly', true);

                                }else{
                                    $('#rating-response').text(res.message);
                                    if($('#rating-response').hasClass('rate-success')){
                                        $('#rating-response').removeClass('rate-success');
                                    }
                                    $('#rating-response').addClass('rate-fail');                                
                                }



                        });
                    }
                }
            });
        });

    </script>


    <script type="text/x-magento-init">
        {
            "[data-rating-role=rating-placeholder]": {
                "FME_Prodfaqs/js/barrating":
                    {}
            }
        }
    </script>


<!-- ----------------------------------------------------------------------------    -->

 <script>

        require([
            'jquery',
            'FME_Prodfaqs/js/jquery.thumbs'
            ], function ($) {

            $('.js-rating-simple').thumbs();
               $('.js-rating').thumbs({
             onLike: function (value,value2,faq) {
               
               
                
                $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getLikesAjaxUrl() ?>",
                                data: { value: value, value2: value2 ,faq: faq}
                        }).done(function( res ) {
                                if(res.error === false){

                                    $('#rating-response').text(res.message);
                                    if($('#rating-response').hasClass('rate-fail')){
                                        $('#rating-response').removeClass('rate-fail');
                                    }
                                    $('#rating-response').addClass('rate-success');
                                                                 
                                }
                                else{
                                     $('#rating-response').text(res.message);
                                    if($('#rating-response').hasClass('rate-success')){
                                        $('#rating-response').removeClass('rate-success');
                                    }
                                    $('#rating-response').addClass('rate-fail');
                                }

                                  

                        });
             },
             onDislike: function(value,value2,faq) {
                

                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getLikesAjaxUrl() ?>",
                                data: { value: value2, value2: value ,faq: faq}
                        }).done(function( res ) {
                                if(res.error === false){

                                    $('#rating-response').text(res.message);
                                    if($('#rating-response').hasClass('rate-fail')){
                                        $('#rating-response').removeClass('rate-fail');
                                    }
                                    $('#rating-response').addClass('rate-success');
                                                                 
                                }
                                else{
                                     $('#rating-response').text(res.message);
                                    if($('#rating-response').hasClass('rate-success')){
                                        $('#rating-response').removeClass('rate-success');
                                    }
                                    $('#rating-response').addClass('rate-fail');
                                }

                                  

                        });
             }
            });
        });

    </script>




<?php } ?>


<?php if(($block->isAskQuestionEnable() && $block->isAskQuestionAllowed()) || ($block->isAskAnswerEnable() && $block->isAskAnswerAllowed()) ){ ?>

    <script type="text/x-magento-init">
        {        
            "[data-role=popup]": {
                "FME_Prodfaqs/js/mobile":
                    {}
            }
        }
    </script>

    <script>

        require([
            'jquery',
            'mobile'], function ($) {

                $('.popup-with-form').magnificPopup({
                      type: 'inline',
                      preloader: false,
                      focus: '#name',

                      // When elemened is focused, some mobile browsers in some cases zoom in
                      // It looks not nice, so we disable it:
                      callbacks: {
                        beforeOpen: function() {
                          if($(window).width() < 700) {
                            this.st.focus = false;
                          } else {
                            this.st.focus = '#name';
                          }
                        }
                      }
                });

        });



        require([
            'jquery'
            ], function ($) {

                

                $( "#fme-ask-question-form-wraper" ).on('submit', function( event ) {


                    var exists = document.getElementById("g-recaptcha-response");

            if(exists == null){
                       var form = $( "#fme-ask-question-form" );
                        $("#progress-loader").addClass('progress-loader');  
                        
                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getFaqPostUrl() ?>",
                                data: form.serialize()
                        }).done(function( res ) {

                                if(res.error === false){

                                    $('#faq-response').text(res.message);
                                    if($('#faq-response').hasClass('rate-fail')){
                                        $('#faq-response').removeClass('rate-fail');
                                    }
                                    $('#faq-response').addClass('rate-success');


                                }else{
                                    $('#faq-response').text(res.message);
                                    if($('#faq-response').hasClass('rate-success')){
                                        $('#faq-response').removeClass('rate-success');
                                    }
                                    $('#faq-response').addClass('rate-fail');                                
                                }   
                                
                                $("#progress-loader").removeClass('progress-loader');  
                        });

                    event.preventDefault();
            }
        
             else{

            var check = document.getElementById("g-recaptcha-response").value;
           
                if(check=='' || check == null){
                   
                }
                else{
                   
                       var form = $( "#fme-ask-question-form" );
                        $("#progress-loader").addClass('progress-loader');  
                        
                        $.ajax({
                                method: "POST",
                                dataType: "json",
                                url: "<?php echo $block->getFaqPostUrl() ?>",
                                data: form.serialize()
                        }).done(function( res ) {

                                if(res.error === false){

                                    $('#faq-response').text(res.message);
                                    if($('#faq-response').hasClass('rate-fail')){
                                        $('#faq-response').removeClass('rate-fail');
                                    }
                                    $('#faq-response').addClass('rate-success');


                                }else{
                                    $('#faq-response').text(res.message);
                                    if($('#faq-response').hasClass('rate-success')){
                                        $('#faq-response').removeClass('rate-success');
                                    }
                                    $('#faq-response').addClass('rate-fail');                                
                                }   
                                
                                $("#progress-loader").removeClass('progress-loader'); 

                                
                        });

                    event.preventDefault();
                }
            }


                });



            });


    
     
    
         function myFunction() {
        var exists = document.getElementById("g-recaptcha-response");

            if(exists == null){
                    
            }
        
             else{

            var check = document.getElementById("g-recaptcha-response").value;
           // alert(check);
                if(check=='' || check == null){
                    document.getElementById("recaptcha").style.border = "1px solid #ea0e0e";
                    return false;
                }
                else{
                    document.getElementById("recaptcha").style.border = "none";
                    return true;
                }
            }
            
   
}

 function myFunction2(val) {
        
        var count = document.getElementById("count"+val).value;
        var exists = document.getElementById("g-recaptcha-response-"+count);

        
        
         
            if(exists == null){
                    
            }
        
             else{
              document.getElementById("recaptcha2"+val).style.display ="inline-block";
              
            var check = document.getElementById("g-recaptcha-response-"+count).value;
           // alert(check);
                if(check=='' || check == null){
                    document.getElementById("recaptcha2"+val).style.border = "1px solid #ea0e0e";
                    
                }
                else{
                    document.getElementById("recaptcha2"+val).style.border = "none";
                     
                    
                }



                var myForm = document.getElementById("fme-ask-answer-form"+val);
    //Extract Each Element Value
    
                if(myForm.elements[6].value == '' || myForm.elements[5].value == null){
                    
                    document.getElementById("customer_name").style.border = "1px solid #ea0e0e";
                    
                }
                else{
                   
                     document.getElementById("customer_name").style.border = "1px solid #c2c2c2";
                     
                    
                }

                if(myForm.elements[7].value == '' || !validateForm(myForm.elements[7].value)){
                    
                    document.getElementById("customer_email").style.border = "1px solid #ea0e0e";
                    
                }
                else{
                    
                     document.getElementById("customer_email").style.border = "1px solid #c2c2c2";
                     
                }

                if(myForm.elements[8].value == '' || myForm.elements[8].value == null){
                   
                    document.getElementById("answer").style.border = "1px solid #ea0e0e";
                    
                }
                else{
                     
                     document.getElementById("answer").style.border = "1px solid #c2c2c2";
                    
                }



                if(check=='' || myForm.elements[6].value == '' || myForm.elements[7].value == '' || myForm.elements[8].value == '' || !validateForm(myForm.elements[7].value)){
                    return false;
                }
                else{
                    return true;
                }

               
              
              
            }


    
   



            
            return false;
}

  function validateForm(email) {
    var x = email;
    var atpos = x.indexOf("@");
    var dotpos = x.lastIndexOf(".");
    if (atpos<1 || dotpos<atpos+2 || dotpos+2>=x.length) {
        return false;
    }
    else{
        return true;
    }
}


    </script>

    
<?php } ?>
 <script src="https://www.google.com/recaptcha/api.js?onload=capt?render=capt?explicit" async defer></script>  

<style type="text/css">
    
    #recaptcha {
  display: inline-block;
  position: relative;
     
  
}

 #recaptcha2 {
 display: inline-block;
  position: relative; 
  
  
}


</style>